carrito/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detail.as_view(),name="cart_detail"),
	url(r'^add/(?P<product_id>\d+)/$', views.AddProd.as_view(), name="cart_add"),
	url(r'^remove/(?P<product_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Home.as_view(), name="home"),
]

nikestore/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from productos import urls as productUrls
from carrito import urls as cartUrls
from orders import urls as orderUrls
from main import urls as UrlsMain
#payment
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^products/',include(productUrls, namespace='products')),
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}),

    
    url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),
    url(r'^', include(UrlsMain,namespace="home")), 

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="base.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),

]

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^create/$',views.CreateOrder.as_view(), name="create"),
]			

productos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	
	url(r'^category/(?P<category>[-\w]+)/$', views.ListView.as_view(), name="category"),
	url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name='detalle'),
	url(r'^$', views.ListView.as_view(), name='products'),


]

carrito/forms.py
from django import forms

CHOICES = ((i,str(i)) for i in range(1,21))

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
	update = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

carrito/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CartAddProductForm
from django.core.urlresolvers import reverse
from django.views.generic import View
from .cart import Cart
from productos.models import Product


class AddProd(View):
	def post(self,request,product_id):
		cart = Cart(request)
		product = get_object_or_404(Product,id=product_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			cart.add(product=product,
				quantity=cd['quantity'],
				update_quantity=cd['update'])
		#return redirect('cart:cart_detail')
		#if reverse(request.path) == '/products/':
		return redirect('products:products')
		#else:
		#	return redirect('products:detalle product.id')
class Remove(View):
	def get(self,request,product_id):
		cart = Cart(request)
		product = get_object_or_404(Product,id=product_id)
		cart.remove(product)
		return redirect('cart:cart_detail')

class Detail(View):
	def get(self,request):
		cart = Cart(request)
		form = CartAddProductForm()
		context={
		'cart':cart,
		'form':form
		}
		return render(request,'cart/detail.html',context)

carrito/templates/cart/detail.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<section class="carrito">
<h1>Compra, compra compraaaaaaaaaaaaaa</h1>
<table >
	<thead>
		<tr>
			<th>Image</th>
			<th>Product</th>
			<th>Quantity</th>
			<th>Remove</th>
			<th>Price</th>
			<th>SubTotal</th>
		</tr>
	</thead>
	<tbody>
		{%for item in cart%}
			{%with product=item.product%}
			<tr>
				<td>
					<img src="/media/{{product.image.url}}" width="200" height="200">
				</td>
				<td>
					{{product.name}}
				</td>
				<td>
					{{item.quantity}}
					<form action="{%url 'cart:cart_add' product.id%}" method="post">
						{% csrf_token %}
						{{form.as_p}}
						<input type="submit" value="Update">
					</form>

				</td>
				<td>
					<a href="{%url 'cart:cart_remove' product.id%}">Remove</a>
				</td>
				<td>
					$ {{item.price}}
				</td>
				<td>
					$ {{item.total_price}}
				</td>
			</tr>
			{%endwith%}
		{%endfor%}
		<tr>
			<td><h3>Total</h3></td>
			<td colspan="4"></td>
			<td>$ {{cart.get_total_price}}</td>
		</tr>
	</tbody>
</table>

<a href="{%url 'products:products'%}"><button>Keep buying</button></a>
<a href="{%url 'orders:create'%}"><button>Pay</button></a>
</section>
{%endblock content%}