carrito/urls.py
from django.conf.urls import url
from . import views


urlpatterns=[
	url(r'^$', views.Detail.as_view(),name="cart_detail"),
	url(r'^add/(?P<product_id>\d+)/$', views.AddProd.as_view(), name="cart_add"),
	url(r'^remove/(?P<product_id>\d+)/$', views.Remove.as_view(), name="cart_remove")
	
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.Home.as_view(), name="home"),
]

nikestore/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.views.static import serve
from django.contrib import admin
from productos import urls as productUrls
from carrito import urls as cartUrls
from orders import urls as orderUrls
from main import urls as UrlsMain
#payment
from paypal.standard.ipn import urls as paypalUrls
from payment import urls as paymentUrls
#for socialauth
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

SOCIAL_AUTH_URL_NAMESPACE = 'social'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(cartUrls, namespace="cart")),
    url(r'^products/',include(productUrls, namespace='products')),
    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}),

    
    url(r'^orders/', include(orderUrls, namespace="orders")),
    url(r'^paypal/', include(paypalUrls)),
    url(r'^payment/', include(paymentUrls,namespace='payment')),
    url(r'^', include(UrlsMain,namespace="home")), 

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
    # Home URL
    url(r'^$', TemplateView.as_view(template_name="base.html"), name="home"),
    # Logout URL
    url(
        r'^users/logout/$',
        logout,
        {'next_page': '/products'},
        name="user-logout"),

]

productos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	
	url(r'^category/(?P<category>[-\w]+)/$', views.ListView.as_view(), name="category"),
	url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name='detalle'),
	url(r'^$', views.ListView.as_view(), name='products'),


]

templates/base.html
{%load static%}
{%load product_tags%}
{%load profile_tag%}
<!DOCTYPE html>
<html>
<head>
	<title>
		{%block titulo%}
		NikeStore
		{%endblock titulo%}
	</title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/base.css'%}">
</head>
<body>
<nav>
	<a href="{%url 'home:home'%}"><img src="/static/images/nike.jpg" width="150" height="100"></a>
<!-- Links para filtrar los resultados de productos -->
	<div>
		<ul>

			{%categories as cats%}
			{%for cat in cats%}
			<li><a href="{%url 'products:category' cat.category%}"><h1>{{cat.category}}</h1></a></li>
			{%empty%}
			<h2>No hay</h2>
			{%endfor%}	
	</div>

		
	</ul>

	<p>
		
		{%with total_items=cart|length%}
		{%if cart|length > 0%}
		Tu carrito:<a href="{%url 'cart:cart_detail'%}">
			{{total_items}} item{{total_items|pluralize}}, $ {{cart.get_total_price}}
		</a>
		{%else%}
		the cart is empty
		{%endif%}
		{%endwith%}
	</p>
	<div class="user">
		<p>
			{% if user and not user.is_anonymous %}
			Buy Mr. {{ user.get_full_name }}.
			<!--{{request.user.email}}-->
			<img src="http://graph.facebook.com/{%image_profile request%}/picture?type=large">

 			<a href="{% url 'user-logout' %}">Logout</a>
 
 			{% else %}
			 <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
			 Enter with Facebook
			 </a>
			 {% endif %}
		</p>
	</div>
</nav>

<div class="buy">
	<a href="{%url 'products:products'%}"><h1>JUST BUY IT</h1></a>
</div>


{%block content%}
{%endblock content%}


{%block scripts%}
{%endblock scripts%}
</body>
</html>